### ISSUE TITLE
Extend error message for missing docstring

### ISSUE THREAD

**Issue by RobinU434** [RobinU434/PyArgWriter#17]
Error message for missing docstring in class definition not  comprehensive

```bash
Traceback (most recent call last):
  File "/home/robin/miniconda3/envs/c2c/bin/pyargwriter", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/robin/miniconda3/envs/c2c/lib/python3.13/site-packages/pyargwriter/main.py", line 45, in main
    if not execute(args):
           ~~~~~~~^^^^^^
  File "/home/robin/miniconda3/envs/c2c/lib/python3.13/site-packages/pyargwriter/main.py", line 27, in execute
    arg_pars_writer.generate_parser(**args)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home/robin/miniconda3/envs/c2c/lib/python3.13/site-packages/pyargwriter/process.py", line 101, in generate_parser
    self.parse_code(files, None)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/robin/miniconda3/envs/c2c/lib/python3.13/site-packages/pyargwriter/process.py", line 41, in parse_code
    self._parser.parse_tree(tree, file)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/robin/miniconda3/envs/c2c/lib/python3.13/site-packages/pyargwriter/utils/code_parser.py", line 243, in parse_tree
    class_name, module_args, help = self._get_class_signature(node)
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/robin/miniconda3/envs/c2c/lib/python3.13/site-packages/pyargwriter/utils/code_parser.py", line 108, in _get_class_signature
    help_message = ast.get_docstring(node).split("\n")[0]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by RobinU434** [comment]
Make error message more understandable if docstring is deprecated or can't be read -> maybe fall back as if there was no docstring after all but put out a logging.error message
